# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zBN9m0VgrdnAqnTs2cu2u1dPXhBAD3Tl
"""

from google.colab import drive
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

drive.mount('/content/gdrive')

dados = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/IA/diabetes.csv')

dados.info()

dados.head()

# Substitui os valores faltantes

dados['Glucose'] = dados['Glucose'].replace(0, dados['Glucose'].mode()[0])

dados['BloodPressure'] = dados['BloodPressure'].replace(0, dados['BloodPressure'].median())

dados['SkinThickness'] = dados['SkinThickness'].replace(0, dados['SkinThickness'].median())

dados['Insulin'] = dados['Insulin'] .replace(0, dados['Insulin'].median())

dados['BMI'] = dados['BMI'].replace(0, dados['BMI'].median())

dados.describe()

correlacao = dados.corr(numeric_only=True).round(2)
plt.figure(figsize=(10,5))
sns.heatmap(correlacao,annot=True, fmt = ".2f", cmap = "coolwarm")

X = dados.drop(["Outcome"] ,axis="columns")
y = dados['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1337, shuffle=True)

modelo = MLPClassifier(max_iter=20000, activation='logistic',verbose=True)

modelo.fit(X_train, y_train)
y_pred = modelo.predict(X_test)
matriz = confusion_matrix(y_test, y_pred)
print(matriz)
relatorio = classification_report(y_test, y_pred)
print("teste")
print(relatorio)

print("teste")
y_pred = modelo.predict(X_train)
matriz = confusion_matrix(y_train, y_pred)
print(matriz)
relatorio = classification_report(y_train, y_pred)
print(relatorio)



"""# Referências
JOSHI, G. Diabetes Prediction using Machine Learning — Python | by Gopal Joshi | Geek Culture | Medium.  Disponível em: <https://medium.com/geekculture/diabetes-prediction-using-machine-learning-python-23fc98125d8>. Acesso em: 04 dez. 2023.

Diabetes Prediction using Machine Learning. - DEV Community.  Disponível em: <https://dev.to/heyfunmi/diabetes-prediction-using-machine-learning-3kbc>. Acesso em: 04 dez. 2023.

Project 2: Diabetes Prediction using Machine Learning with Python | End To End Python ML Project - YouTube.  Disponível em: <https://www.youtube.com/watch?v=xUE7SjVx9bQ>. Acesso em: 04 dez. 2023.

RNACancerMama.ipynb - Colaboratory.  Disponível em: <https://colab.research.google.com/drive/1GLMAzqh9yqg2Ohm_z7lnwqi939cBOwQS?usp=sharing#scrollTo=2oRfZNSq0U4C>. Acesso em: 04 dez. 2023.
"""